try:
    result = 45/5
except:
    print('Error found')
finally:
    print('Finally here')

print('Done')